// // -----------------------------Start: 56_2---------------------------------------
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       // (1) import from heroui theming switch themes
//       // class="dark" data-theme="dark"
//       // (3) then create src/components/Navbar.jsx
//       data-theme="dark"
//       // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//       // (2)
//       className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
        
//         {/* {children} */}
//         {/* (8)st */}
//         <Navbar/>
//         <main>{children}</main>
//         {/* (8)en then (start: 56_3)go to Navbar.jsx file*/}
        
      
//       </body>
//     </html>
//   );
// }

// // ---------------------End:56_2-(1) to () --------------------------------
// -----------------------------Start: 56_3---------------------------------------
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
      data-theme="dark"
      
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar/>
        <main>{children}</main>
        {/* (5) then go to Footer*/}
        <Footer/>
           
      
      </body>
    </html>
  );
}

// ---------------------End:56_3-(1) to () --------------------------------

